baseURL: "https://m0h-nnad.github.io/fsh-mms-hugo-test/"
theme: "up-business-theme"
languageCode: "en-us"

title: "fsh mms"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "fsh mms"
  description: "Powering the Future of Fintech"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2022 FSH MMS  All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About"
      url: "/#"
      weight: 2

    - name: "Services"
      url: "/#"
      weight: 3

    - name: "Contact"
      url: "/#"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About"
      url: "/#"
      weight: 2

    - name: "Services"
      url: "/#"
      weight: 3

    - name: "Contact"
      url: "/#"
      weight: 4

taxonomies:
  series: "series"
  tags: "tags"
