on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on:ubuntu-latest


    steps:
    -uses:action/checkout@v2

 -name: Hugo setup
  # You may pin to the exact commit or the version.
  # uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f
  uses: peaceiris/actions-hugo@v3.0.0
  with:
    extended: true
-name: build hugo site
  run: hugo

-name: deploy to GIT pages
  # You may pin to the exact commit or the version.
  # uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564
  uses: crazy-max/ghaction-github-pages@v4.0.0
  with:
    build_dir: public
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


  
    
